webapp/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static


app_name = 'webapp'

urlpatterns = [
    path('index/',views.indexView,name='index'),
    path('search-basic/',views.search_basic, name='basicSearch'),
    path('search-advanced/',views.search_advanced, name='advancedSearch'),
    path('index/about/',views.aboutView, name='about'),
    #path('result/', views.saveToTable, name='showResult'),
    path('<int:id>/',views.detailView,name='detail'),
    path('update-rating/', views.updateView, name='update'),
    path('exportCSV/', views.exportCSV, name='exportCSV'),
    #path('distance/',views.getDistance,name='distance'),
    path('resetRatings/', views.resetRatings, name='resetRatings')
]

webapp/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Smart Rent| Aggregating rental reviews and information</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <!--<link href="{% static 'webapp/css/bootstrap.min.css' %}" rel="stylesheet">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Custom CSS -->
    <link href="{% static 'webapp/css/landing-page.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <!-- Custom Fonts -->
    <link href="{% static 'webapp/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


</head>
<body>
    <!-- Navigation Bar-->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'webapp:index' %}">Smart Rent</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
{#                        <a href="#about">About</a>#}
                        <a href="{% url 'webapp:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'webapp:index' %}#services">Search House</a>
                    </li>
                    <li>
                        <a href="{% url 'webapp:index' %}#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block body%}
    {% endblock %}


        <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="{% url 'webapp:index' %}">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="{% url 'webapp:about' %}">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="{% url 'webapp:index' %}#services">Search</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="{% url 'webapp:index' %}#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Smart Rent 2018. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'webapp/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'webapp/js/bootstrap.min.js' %}"></script>

</body>

</html>

webapp/templates/webapp/exportCSV.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>exportCSV</title>
</head>
<body>
    <h1>export succeed</h1>
</body>
</html>

webapp/templates/webapp/resetRatings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>resetRating</title>
</head>
<body>
    <h1>All ratings have been randomly reset</h1>
</body>
</html>

webapp/templates/webapp/searchAdvanced.html
{% extends 'webapp/base.html' %}

{% block title %}Advance Search Result Page {% endblock %}

{% block body %}
<link href="https://fonts.googleapis.com/css?family=Noticia+Text" rel="stylesheet">
<style>
    body {
        font-family: 'Roboto';
    }

    .listing-box h4 {
        line-height: 30px;
        color: #e55122
    }

    .listing-box {
        background: #f2f4f4;
        padding: 20px;
        float: left;
        width: 70%;
        height: 410px
    }

    .poperty-details-iob {
        margin: 5px 0;
        padding: 8px 0;
        display: inline-block;
        border-top: #e5e5e5 1px solid;
        border-bottom: #e5e5e5 1px solid;
        width:;
    }

    .poperty-details-iob li {
        margin: 0;
        padding: 8px 15px;
        display: inline-block;
        font-family: 'Roboto';
        color: #333;
        border-right: #e5e5e5 1px solid;
    }

    .poperty-details-iob li span {
        font-size: 22px;
        color: #000;
    }

    .listing-box p {
        font-size: 12px;
        color: #838383;
    }

    .list-of-ratings {
        margin: auto;
        padding: 0;
        display: block;
        width: fit-content;
        float: left;
        position: relative;
    }

    .list-of-ratings li {
        margin: 0;
        padding: 10px 15px 0px 0px;
        display: block;
        width: 100%;
        font-size: 16px;
    }

    .mr-iob-blr {
        margin-top: 20px;
    }

    .listing-box ul li a {
        color: #e55122;
    }

    /*.cls-for-btn-listing{margin:auto; padding:0; display:inline-block; text-align:center; width:100%; margin-top:130px;}*/
    /*.cls-for-btn-listing li{margin:auto; padding:0; display:inline-block; }*/
    /*.cls-for-btn-listing li a{margin:auto; padding:10px 15px; display:inline-block; background:#e55122 !important; border-radius:20px; color:#fff !important; }*/
    .star-list-iob {
        margin: 16px 0;
        padding: 0;
        display: block;
        position: relative;
        float: right
    }

    .star-list-iob li {
        margin: 0;
        padding: 0 3px;
        display: block;
    }

    /*.rating-box-iob{background:#e55122; padding:8px; border-radius:5px; position:absolute; color:#fff; right:20px; margin-top:40px;}*/
    .rating-box-iob {
        background: #e55122;
        padding: 4px;
        border-radius: 5px;
        color: #fff;
        right: 20px;
        margin-top: 40px;
    }

    #pricetag {
        color: #03a1d1;
        font-size: large
    }

    .detail {
        margin: 10px;
        padding: 10px 15px;
        display: inline-block;
        background-color: #23527c;
        border-radius: 20px;
        color: #fff !important;
        /*float: right*/
    }

    .agentimg {
        float: left;
    }

    .col-md-3 {
        width: 50%;
    }

    .agentname {
        margin: 30px 10px 10px 10px;
    }

    .detail:hover {
        background-color: #d4d4d4;
    }

    #noresult {
        height: 600px;
        text-align: center;
        position: relative;

    }

    #nomatch {
        position: absolute;
        left: 50%;
        transform: translateX(-50%);
        -webkit-transform: translateX(-50%);
        align-content: center;

    }
        a {
        color:#e55122;
    }
</style>


<hr class="intro-divider">
<div style="background-color:#e8e8e8">
    {% if result_advanced %}

    {% for resource in result_advanced %}
    <section class="listing-page-builing">
        <div class="container">
            <div class="row">
                <div class="listing-box">

                    <div class="col-lg-5 col-md-6 mr-iob-blr">

                        <img alt="image" class="img-responsive" src="{{ resource.property.house_img }}">
                        <br>
                        <a href="{% url 'webapp:detail' resource.id %}" class="detail" role="button">View Detail</a>
                        <br>
                        <hr>

                    </div>


                    <div class="col-md-6">
                        <h4><strong><a href="{% url 'webapp:detail' resource.id %}">{{ resource.property.address }} </a></strong><br/>
                        </h4>
                        <ul class="poperty-details-iob">
                            <li id="pricetag">${{ resource.price }}</li>
                            <li>{{ resource.property.no_bed }} <i class="fa fa-bed" style="font-size:24px"></i></li>
                            <li>{{ resource.property.no_bath }} <i class="fa fa-bath" style="font-size:24px"></i></li>
                            <br> <img class="agentimg img-circle img-responsive" src="{{resource.agency.agent_img}}"
                                      width="30%" height="30%">
                            <p class="agentname">{{resource.agency.name}}</p>
                            <li></li>
                        </ul>

                        <ul class="list-of-ratings">

                            <li><br/><strong>Agent Ratings:&nbsp&nbsp</strong><span
                                    class="rating-box-iob" id="aratings-{{forloop.counter}}">5</span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<strong>
                                Property Ratings:&nbsp&nbsp</strong><span class="rating-box-iob"
                                                                          id="pratings-{{forloop.counter}}">2</span></li>

                            <!--<li><strong>Property Ratings:&nbsp&nbsp</strong><span class="rating-box-iob"-->
                                                                                       <!--id="pratings-{{forloop.counter}}">2</span>-->
                            <!--<br>-->
                            <!--</li>-->
                            <li id="showdistance-{{forloop.counter}}", style="font-family:'Noticia Text', serif; font-size: 13px; color:#23527c"><strong>Distance from <span
                                    id="uniname-{{forloop.counter}}">Uni</span>:  <span id="distance-{{forloop.counter}}">1000m</span>m</strong>
                            </li>
                            <li id="showduration-{{forloop.counter}}", style="font-family:'Noticia Text', serif; font-size: 13px; color:#23527c "><strong>Duration of walk: <span id="duration-{{forloop.counter}}">1000m</span></strong>
                            </li>
                        </ul>

                    </div>


                </div>
            </div>
        </div>
    </section>

    <script type="text/javascript">

        var uni = "{{uniName}}";
        console.log(uni);
        document.getElementById("uniname-{{forloop.counter}}").innerHTML = uni;
        if (uni === "RMIT University") {
            var distance1 = "{{resource.property.distance_rmit}}";
            var duration1 = "{{resource.property.duration_rmit}}";
            console.log("{{resource.property.distance_rmit}}");
            document.getElementById("distance-{{forloop.counter}}").innerHTML = distance1;
            document.getElementById("duration-{{forloop.counter}}").innerHTML = duration1;
        } else if (uni === "University of Melbourne") {
            var distance2 = "{{resource.property.distance_umel}}";
            var duration2 = "{{resource.property.duration_umel}}";
            document.getElementById("distance-{{forloop.counter}}").innerHTML = distance2;
            document.getElementById("duration-{{forloop.counter}}").innerHTML = duration2;
        } else {
            document.getElementById("showdistance-{{forloop.counter}}").style.display = "none";
            document.getElementById("showduration-{{forloop.counter}}").style.display = "none";
        }

        var loc_rating = "{{resource.property.loc_rating}}";
        var fac_rating = "{{resource.property.fac_rating}}";
        var tran_rating = "{{resource.property.tran_rating}}";
        var index = "{{forloop.counter}}";
        var property_avg = (Number(loc_rating) + Number(fac_rating) + Number(tran_rating)) / 3;
        var fri_rating = "{{resource.agency.fri_rating}}";
        var res_rating = "{{resource.agency.res_rating}}";
        var bond_rating = "{{resource.agency.bond_rating}}";
        var agent_avg = (Number(fri_rating) + Number(res_rating) + Number(bond_rating)) / 3;
        document.getElementById('aratings-{{forloop.counter}}').innerHTML = agent_avg.toFixed(1);
        document.getElementById('pratings-{{forloop.counter}}').innerHTML = property_avg.toFixed(1);
    </script>


    <hr>


    {% endfor %}

    {% else %}
    <div id="noresult">
        <br>
        <br>
        <br>
        <br>

        <h1 id="nomatch">No Result Match</h1>

    </div>


    {% endif %}


</div>


{% endblock %}

webapp/templates/webapp/searchBasic.html
{% extends 'webapp/base.html' %}

{% block title %}Basic Search Result Page {% endblock %}

{% block body %}
<link href="https://fonts.googleapis.com/css?family=Noticia+Text" rel="stylesheet">
<style>
    body {
        font-family: 'Roboto';
    }

    .listing-box h4 {
        line-height: 30px;
        color: #e55122
    }

    .listing-box {
        background: #f2f4f4;
        padding: 20px;
        float: left;
        width: 70%;
        height: 410px
    }

    .poperty-details-iob {
        margin: 5px 0;
        padding: 8px 0;
        display: inline-block;
        border-top: #e5e5e5 1px solid;
        border-bottom: #e5e5e5 1px solid;
        width:;
    }

    .poperty-details-iob li {
        margin: 0;
        padding: 8px 15px;
        display: inline-block;
        font-family: 'Roboto';
        color: #333;
        border-right: #e5e5e5 1px solid;
    }

    .poperty-details-iob li span {
        font-size: 22px;
        color: #000;
    }

    .listing-box p {
        font-size: 12px;
        color: #838383;
    }

    .list-of-ratings {
        margin: auto;
        padding: 0;
        display: block;
        width: fit-content;
        float: left;
        position: relative;
    }

    .list-of-ratings li {
        margin: 0;
        padding: 10px 15px 0px 0px;
        display: block;
        width: 100%;
        font-size: 16px;
    }

    .mr-iob-blr {
        margin-top: 20px;
    }

    .listing-box ul li a {
        color: #e55122;
    }


    /*.cls-for-btn-listing{margin:auto; padding:0; display:inline-block; text-align:center; width:100%; margin-top:130px;}*/
    /*.cls-for-btn-listing li{margin:auto; padding:0; display:inline-block; }*/
    /*.cls-for-btn-listing li a{margin:auto; padding:10px 15px; display:inline-block; background:#e55122 !important; border-radius:20px; color:#fff !important; }*/
    .star-list-iob {
        margin: 16px 0;
        padding: 0;
        display: block;
        position: relative;
        float: right
    }

    .star-list-iob li {
        margin: 0;
        padding: 0 3px;
        display: block;
    }

    /*.rating-box-iob{background:#e55122; padding:8px; border-radius:5px; position:absolute; color:#fff; right:20px; margin-top:40px;}*/
    .rating-box-iob {
        background: #e55122;
        padding: 4px;
        border-radius: 5px;
        color: #fff;
        right: 20px;
        margin-top: 40px;
    }

    #pricetag {
        color: #03a1d1;
        font-size: large
    }

    .detail {
        margin: 10px;
        padding: 10px 15px;
        display: inline-block;
        background-color: #23527c;
        border-radius: 20px;
        color: #fff !important;
        /*float: right*/
    }

    .agentimg {
        float: left;
    }

    .col-md-3 {
        width: 50%;
    }

    .agentname {
        margin: 30px 10px 10px 10px;
    }

    .detail:hover {
        background-color: #d4d4d4;
    }

    #noresult {
        height: 600px;
        text-align: center;
        position: relative;

    }

    #nomatch {
        position: absolute;
        left: 50%;
        transform: translateX(-50%);
        -webkit-transform: translateX(-50%);
        align-content: center;

    }
    a {
        color:#e55122;
    }
</style>


<hr class="intro-divider">
<div style="background-color:#e8e8e8">
    {% if result_basic %}

    {% for resource in result_basic %}
    <section class="listing-page-builing">
        <div class="container">
            <div class="row">
                <div class="listing-box">

                    <div class="col-lg-5 col-md-6 mr-iob-blr">

                        <img alt="image" class="img-responsive" src="{{ resource.property.house_img }}">
                        <br>
                        <a href="{% url 'webapp:detail' resource.id %}" class="detail" role="button">View Detail</a>
                        <br>
                        <hr>

                    </div>


                    <div class="col-md-6">
                        <h4 id="address"><a href="{% url 'webapp:detail' resource.id %}">{{ resource.property.address }} </a></h4>
                        <ul class="poperty-details-iob">
                            <li id="pricetag">${{ resource.price }}</li>
                            <li>{{ resource.property.no_bed }} <i class="fa fa-bed" style="font-size:24px"></i></li>
                            <li>{{ resource.property.no_bath }} <i class="fa fa-bath" style="font-size:24px"></i></li>
                            <br> <img class="agentimg img-circle img-responsive" src="{{resource.agency.agent_img}}"
                                      width="30%" height="30%">
                            <p class="agentname">{{resource.agency.name}}</p>
                            <li></li>
                        </ul>

                        <ul class="list-of-ratings">

                            <li><br/><strong>Agent Ratings:&nbsp&nbsp</strong><span
                                    class="rating-box-iob" id="aratings-{{forloop.counter}}">5</span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<strong>
                                Property Ratings:&nbsp&nbsp</strong><span class="rating-box-iob"
                                                                          id="pratings-{{forloop.counter}}">2</span></li>

                            <!--<li><strong>Property Ratings:&nbsp&nbsp</strong><span class="rating-box-iob"-->
                                                                                       <!--id="pratings-{{forloop.counter}}">2</span>-->
                            <!--<br>-->
                            <!--</li>-->
                            <li id="showdistance-{{forloop.counter}}", style="font-family:'Noticia Text', serif; font-size: 13px; color:#23527c"><strong>Distance from <span
                                    id="uniname-{{forloop.counter}}">Uni</span>:  <span id="distance-{{forloop.counter}}">1000m</span>m</strong>
                            </li>
                            <li id="showduration-{{forloop.counter}}", style="font-family:'Noticia Text', serif; font-size: 13px; color:#23527c "><strong>Duration of walk: <span id="duration-{{forloop.counter}}">1000m</span></strong>
                            </li>
                        </ul>

                    </div>


                </div>
            </div>
        </div>
    </section>

    <script type="text/javascript">

        var uni = "{{uniName}}";
        console.log(uni);
        document.getElementById("uniname-{{forloop.counter}}").innerHTML = uni;
        if (uni === "RMIT University") {
            var distance1 = "{{resource.property.distance_rmit}}";
            var duration1 = "{{resource.property.duration_rmit}}";
            console.log("{{resource.property.distance_rmit}}");
            document.getElementById("distance-{{forloop.counter}}").innerHTML = distance1;
            document.getElementById("duration-{{forloop.counter}}").innerHTML = duration1;
        } else if (uni === "University of Melbourne") {
            var distance2 = "{{resource.property.distance_umel}}";
            var duration2 = "{{resource.property.duration_umel}}";
            document.getElementById("distance-{{forloop.counter}}").innerHTML = distance2;
            document.getElementById("duration-{{forloop.counter}}").innerHTML = duration2;
        } else {
            document.getElementById("showdistance-{{forloop.counter}}").style.display = "none";
            document.getElementById("showduration-{{forloop.counter}}").style.display = "none";
        }

        var loc_rating = "{{resource.property.loc_rating}}";
        var fac_rating = "{{resource.property.fac_rating}}";
        var tran_rating = "{{resource.property.tran_rating}}";
        var index = "{{forloop.counter}}";
        var property_avg = (Number(loc_rating) + Number(fac_rating) + Number(tran_rating)) / 3;
        var fri_rating = "{{resource.agency.fri_rating}}";
        var res_rating = "{{resource.agency.res_rating}}";
        var bond_rating = "{{resource.agency.bond_rating}}";
        var agent_avg = (Number(fri_rating) + Number(res_rating) + Number(bond_rating)) / 3;
        document.getElementById('aratings-{{forloop.counter}}').innerHTML = agent_avg.toFixed(1);
        document.getElementById('pratings-{{forloop.counter}}').innerHTML = property_avg.toFixed(1);
    </script>


    <hr>


    {% endfor %}

    {% else %}
    <div id="noresult">
        <br>
        <br>
        <br>
        <br>

        <h1 id="nomatch">No Result Match</h1>

    </div>


    {% endif %}


</div>


{% endblock %}

webapp/templates/webapp/searchBasic1.html
{% extends 'webapp/base.html' %}

{% block title %}Basic Search Result Page {% endblock %}

{% block body %}

<style>
    /**** BASE ****/
body {
    color: #888;
}
a {
    color: #03a1d1;
    text-decoration: none!important;
}

/**** LAYOUT ****/
.list-inline>li {
    padding: 0 10px 0 0;
}
.container-pad {
    padding: 30px 15px;
}


/**** MODULE ****/
.bgc-fff {
    background-color: #fff!important;
}
.box-shad {
    -webkit-box-shadow: 1px 1px 0 rgba(0,0,0,.2);
    box-shadow: 1px 1px 0 rgba(0,0,0,.2);
}
.brdr {
    border: 1px solid #ededed;
}

/* Font changes */
.fnt-smaller {
    font-size: .9em;
}
.fnt-lighter {
    color: #bbb;
}

/* Padding - Margins */
.pad-10 {
    padding: 10px!important;
}
.mrg-0 {
    margin: 0!important;
}
.btm-mrg-10 {
    margin-bottom: 10px!important;
}
.btm-mrg-20 {
    margin-bottom: 20px!important;
}

/* Color  */
.clr-535353 {
    color: #535353;
}




/**** MEDIA QUERIES ****/
@media only screen and (max-width: 991px) {
    #property-listings .property-listing {
        padding: 5px!important;
    }
    #property-listings .property-listing a {
        margin: 0;
    }
    #property-listings .property-listing .media-body {
        padding: 10px;
    }
}

@media only screen and (min-width: 992px) {
    #property-listings .property-listing img {
        max-width: 180px;
    }
}


</style>


<hr class="intro-divider">
<div class="container-fluid" style="background-color:#e8e8e8">
        <div class="container container-pad" id="property-listings">


            <div class="row">
                <div class="col-lg-6 col-sm-6">

                    <!-- Begin Listing: 609 W GRAVERS LN-->
                    <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                        <div class="media">
                            <a class="pull-left" href="#" target="_parent">
                            <img alt="image" class="img-responsive" src="http://images.prd.mris.com/image/V2/1/Yu59d899Ocpyr_RnF0-8qNJX1oYibjwp9TiLy-bZvU9vRJ2iC1zSQgFwW-fTCs6tVkKrj99s7FFm5Ygwl88xIA.jpg"></a>

                            <div class="clearfix visible-sm"></div>

                            <div class="media-body fnt-smaller">
                                <a href="#" target="_parent"></a>

                                <h4 class="media-heading">
                                  <a href="#" target="_parent">$1,975,000 <small class="pull-right">609 W Gravers Ln</small></a></h4>


                                <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
                                    <li>4,820 SqFt</li>

                                    <li style="list-style: none">|</li>

                                    <li>5 Beds</li>

                                    <li style="list-style: none">|</li>

                                    <li>5 Baths</li>
                                </ul>

                                <p class="hidden-xs">Situated between fairmount
                                park and the prestigious philadelphia cricket
                                club, this beautiful 2+ acre property is truly
                                ...</p><span class="fnt-smaller fnt-lighter fnt-arial">Courtesy of HS Fox & Roach-Chestnut Hill
                                Evergreen</span>
                            </div>

                            <button class="btn-danger" name="{{ property.address }}"> Detail</button>
{#                            todo select serach result, and go to the detail page#}
{#                            <a href="{% url 'webapp:detail' resource.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>#}
                        </div>
                    </div><!-- End Listing-->





                </div>



            </div><!-- End row -->


        </div><!-- End container -->



{% endblock %}

webapp/templates/webapp/showResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
</head>
<body>
    <h1>Show results here:</h1>
    <p>{{ crawled_info }}</p>
</body>
</html>

webapp/templates/webapp/updateRatings.html
{% extends 'webapp/base.html' %}

{% block title %}Basic Search Result Page {% endblock %}

{% block body %}
<style>
    #showing{
        height:600px;
        width:75%;
        text-align: center;
    }
</style>

<hr class="intro-divider">
<div class="container-fluid" style="background-color:#e8e8e8">

<hr>
<div id="showing">
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>Your ratings have been submitted successfully</h1>
    <h2>Thank you for your feedback</h2>

</div>


</div>

{% endblock %}